### ISSUE TITLE
Missing 5th SSL info in README

### ISSUE THREAD

**Issue by Maritsu** [arindas/manjarno#17] opened 2022-11-08 18:17 UTC
All info is in the title - README.md is missing the latest SSL fuck-up, which has already been mentioned on the website.

**Comment by EmeraldSnorlax** [comment] 2022-11-08 18:22
duplicate of #16

**Comment by arindas** [comment] 2022-11-08 18:26
Closing this since it's a duplicate issue which has already been discussed.

**Closed** 2022-11-08 18:26 UTC
